### ISSUE TITLE
Could wrap this up with a Dockerfile

### ISSUE THREAD

**Issue by mveer1** [niharbansal02/cowin_automation#1]

**Comment by niharbansal02** [comment]
Wrap this up as in the installation and configuration?

**Comment by shreyaskirtane7** [comment]
Correct me if am wrong, but this script generates notif sounds on host machine. Idk how it would work inside a container as in how would the notifs get propagated to the host machine. And since docker works differently on Linux(namespaces) and Windows(VM) it adds to the complexity.

But in case you are seriously interested you can decouple notif methods and data collection methods and add other notif options like email, SMS etc.

**Comment by niharbansal02** [comment]
Yup @shreyaskirtane7, the script generates notif sounds and pop-up notifications on the host machine. If I do everything in a container, the end-user might have to do various changes to allow the propagation of commands through the VM, and can't expect Windows Users to do so, as the complexity there is high.

Yup, email and SMS notifications are on my feature list. I'm learning them on the sides, and it shall be deployed within a few days.
